apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: users-api

  template:
    metadata:
      labels:
        app: users-api

    spec:
      containers:
      - name: users-api

        image: fenixdevs/users-api:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: users-api-secret
              key: aws-access-key

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: users-api-secret
              key: aws-secret-key

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: users-api-secret
              key: jwt-secret

        - name: Redis__Connection
          valueFrom:
            configMapKeyRef:
              name: users-api-config
              key: redis-connection

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10